### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dreaming-augustin** [kPanesar/aws-cpp-sdk-example#2]
Hello,

I just wanted to stop by and say a quick thank you.

I just started using the Amazon Polly c++ sdk, but the official documentation was not quite sufficient enough for a beginner developer like myself, lacking experience working with streams.

I had been struggling for a few days, when I stumbled onto your aws-cpp-sdk-example code, which helped me obtain the breakthrough I needed. 

Thanks a lot for sharing!

**Comment by dreaming-augustin** [comment]
See:
Add more Polly C++ examples / tutorials 
https://github.com/aws/aws-sdk-cpp/issues/968

**Comment by kPanesar** [comment]
@dreaming-augustin Hi, I'm glad it helped! I struggled with it as well in the beginning. AWS can certainly do a much better job at providing proper examples.
